---
device: "$torch.device('cuda' if torch.cuda.is_available() else 'cpu')"
network_def:
  _target_: UNet
  spatial_dims: 3
  in_channels: 1
  out_channels: 2
  channels:
  - 16
  - 32
  - 64
  - 128
  - 256
  strides:
  - 2
  - 2
  - 2
  - 2
  num_res_units: 2
  norm: batch
network: need override
preprocessing:
  _target_: Compose
  transforms:
  - _target_: LoadImaged
    keys: image
  - _target_: EnsureChannelFirstd
    keys: image
  - _target_: ScaleIntensityd
    keys: image
  - _target_: RandRotated
    _disabled_: true
    keys: image
  - _target_: EnsureTyped
    keys: image
dataset:
  _target_: need override
  data: "@_meta_#datalist"
  transform: "@preprocessing"
dataloader:
  _target_: DataLoader
  dataset: "@dataset"
  batch_size: 1
  shuffle: false
  num_workers: 4
inferer:
  _target_: SlidingWindowInferer
  roi_size:
  - 96
  - 96
  - 96
  sw_batch_size: 4
  overlap: 0.5
postprocessing:
  _target_: Compose
  transforms:
  - _target_: Activationsd
    keys: pred
    softmax: true
  - _target_: AsDiscreted
    keys: pred
    argmax: true
  - _target_: SaveImaged
    keys: pred
    meta_keys: image_meta_dict
    output_dir: "@_meta_#output_dir"
evaluator:
  _target_: SupervisedEvaluator
  device: "@device"
  val_data_loader: "@dataloader"
  network: "@network"
  inferer: "@inferer"
  postprocessing: "@postprocessing"
  amp: false
