name: build

on:
  # quick tests for every pull request
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run test
        id: run-test
        run: |
          # set vars
          export MONAI_EXTRA_TEST_DATA=$(pwd)
          export MONAI_PATH=~/MONAI

          # checkout MONAI, pip install requirements and setup
          git clone https://github.com/Project-MONAI/MONAI.git --depth 1 $MONAI_PATH
          cd $MONAI_PATH
          pip install --user --upgrade -r ${MONAI_PATH}/requirements-min.txt
          BUILD_MONAI=0 python setup.py develop  # no compile of extensions

          # run unit test
          python -m unittest -v tests/test_network_consistency.py
