name: Require pull request

on:
  # quick tests for every pull request
  push:
    branches:
      - main
  pull_request:

jobs:
  runtest:
    runs-on: ubuntu-latest
    env:
      MONAI_PATH: ~/MONAI
    steps:
      - name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
      - name: Checkout LFS objects
        run: git lfs checkout
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Clone MONAI and get dependencies
        run: |
          git clone https://github.com/Project-MONAI/MONAI.git --depth 1 $MONAI_PATH
          cd $MONAI_PATH
          pip install --user --upgrade -r requirements-min.txt
          BUILD_MONAI=0 python setup.py develop  # no compile of extensions
      - name: Run unit test
        run: |
          # set vars
          export MONAI_EXTRA_TEST_DATA=$(pwd)
          # run unit test
          cd ${MONAI_PATH}
          python -m unittest -v tests/test_network_consistency.py
