name: Pull Request on Branch Push

on:
  # quick tests for every pull request
  push:
    branches:
      - main
  pull_request:

jobs:
  run_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: run test
        id: run-test
        run: |
          export MONAI_EXTRA_TEST_DATA=$(pwd)
          pwd
          ls $MONAI_EXTRA_TEST_DATA
          export MONAI_PATH=~/MONAI
          git clone https://github.com/Project-MONAI/MONAI.git $MONAI_PATH
          ls $MONAI_PATH
          # export PYTHONPATH=${MONAI_PATH}:$PYTHONPAH
          # pip install --user --upgrade -r ${MONAI_PATH}/requirements-min.txt
          # python -m unittest -v ${MONAI_PATH}/tests/test_network_consistency.py
